from playwright.async_api import async_playwright
import urllib.parse
import requests
import asyncio

async def get_csrf_from_cookie():
    async with async_playwright() as p:
        browser = await p.firefox.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()

        await page.goto("https://amsterdam.mijndak.nl/Woningaanbod", wait_until="networkidle")
        cookies = await context.cookies()

        csrf_token = None
        for cookie in cookies:
            if cookie['name'] == 'nr2Users':
                csrf_token = urllib.parse.unquote(cookie['value']).split('=')[1]+"="
                break

        await browser.close()
        return csrf_token

csrf_token = asyncio.run(get_csrf_from_cookie())

class Constants:
    global csrf_token

    @staticmethod
    def get_headers_payload(oftype, publication_id=0):
        start_headers = {
            'Accept': 'application/json',
            'X-CSRFToken': f'{csrf_token}',
            'Content-Type': 'application/json; charset=UTF-8',
            'Origin': 'https://amsterdam.mijndak.nl',
            'Referer': 'https://amsterdam.mijndak.nl/Woningaanbod',
        }

        start_payload = {
            'versionInfo': {
                'moduleVersion': 'gc5UrXD2cJlgmpzXRSB5nQ',
                'apiVersion': '1zE4YhqCDGCEPhqONhywBA',
            },
            'viewName': 'Overzicht.Woningaanbod',
            'screenData': {
                'variables': {
                    'ActiefTabblad': 0,
                    'Platform': '',
                    'PlatformVersie': '',
                    'AantalVerborgenWoningen': 0,
                    'AdvertentielijstContainerId': '',
                    'MapandFiltersContainerId': '',
                    'Filters': {
                        'Woonplaatsen': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Eigenaren': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'TypeWoning': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'AantalKamers': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Aanbodmodel': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Doelgroep': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Voorzieningen': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Contractvormen': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Toegankelijkheid': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'OnzichtbareFilters': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'MaxPrijs': 0,
                        'MinPrijs': 0,
                        'Sortering': 0,
                        'SorteringIsAscending': False,
                    },
                    'Filters_Basis': {
                        'Woonplaatsen': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Eigenaren': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'TypeWoning': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'AantalKamers': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Aanbodmodel': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Doelgroep': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Voorzieningen': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Contractvormen': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'Toegankelijkheid': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'OnzichtbareFilters': {
                            'List': [],
                            'EmptyListItem': {
                                'Naam': '',
                                'IsGeselecteerd': False,
                                'Id': '0',
                                'Categorie': '',
                                'Aantal': 0,
                                'IsVisible': True,
                                'IsEmptyValue': False,
                            },
                        },
                        'MaxPrijs': 0,
                        'MinPrijs': 0,
                        'Sortering': 0,
                        'SorteringIsAscending': False,
                    },
                    'Filters_ChipList': {
                        'List': [],
                        'EmptyListItem': {
                            'Categorie': '',
                            'Label': '',
                            'IsGroen': False,
                        },
                    },
                    'FilterMenu_Trigger': True,
                    'PublicatieLijst_Basis': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'EinddatumTijd': '1900-01-01T00:00:00',
                            'PublicatieModel': '',
                            'PublicatieModule': '',
                            'PublicatieDatum': '1900-01-01T00:00:00',
                            'Matchpercentage': 0,
                            'VoorlopigePositie': '0',
                            'Foto_Locatie': '',
                            'GepersonaliseerdeHuur': '0',
                            'IsCluster': False,
                            'EenheidSoort': '',
                            'Adres': {
                                'Straatnaam': '',
                                'Huisnummer': 0,
                                'Huisletter': '',
                                'HuisnummerToevoeging': '',
                                'Postcode': '',
                                'Woonplaats': '',
                                'Wijk': '',
                                'PublicatieId': '0',
                            },
                            'Cluster': {
                                'Naam': '',
                                'DetailSoort': '',
                                'Doelgroep': '',
                                'PrijsMinBekend': False,
                                'PrijsMin': '0',
                                'PrijsMaxBekend': False,
                                'PrijsMax': '0',
                                'WoonOppervlakteMinBekend': False,
                                'WoonVertrekkenTotOppMin': 0,
                                'WoonOppervlakteMaxBekend': False,
                                'WoonVertrekkenTotOppMax': 0,
                                'AantalEenheden': 0,
                                'AantalKamersMin': 0,
                                'AantalKamersMax': 0,
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'Eigenaar': '',
                            },
                            'Eenheid': {
                                'DetailSoort': '',
                                'Bestemming': '',
                                'AantalKamers': 0,
                                'TotaleOppervlakte': '0',
                                'WoonVertrekkenTotOpp': '0',
                                'Doelgroep': '',
                                'NettoHuurBekend': False,
                                'NettoHuur': '0',
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'EnergieLabel': '',
                                'EnergieIndex': 0,
                                'Eigenaar': '',
                                'BrutoHuurBekend': False,
                                'Brutohuur': '0',
                                'SubsidiabeleHuur': '0',
                            },
                            'PublicatieLabel': '',
                            'IsBewaard': False,
                            'IsVerborgen': False,
                            'ContractVorm': '',
                            'PublicatieOmschrijving': {
                                'Id': '0',
                                'Tekst': None,
                            },
                            'AantalReactiesOpPublicatie': '0',
                            'HeeftGereageerd': False,
                            'IsIntrekkenReactieToegestaan': False,
                            'RedenNietIntrekkenReactie': '',
                            'PositieAanbiedingsproces': '',
                            'VirtuelePositie': 0,
                            'Opleverdatum': '1900-01-01T00:00:00',
                            'HeeftLift': False,
                            'Verdieping': '',
                            'IsMetGepersonaliseerdeHuur': False,
                            'Voorziening': '',
                            'AanbiedingProcesSoort': '',
                        },
                    },
                    'PublicatieLijst_Gefilterd': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'EinddatumTijd': '1900-01-01T00:00:00',
                            'PublicatieModel': '',
                            'PublicatieModule': '',
                            'PublicatieDatum': '1900-01-01T00:00:00',
                            'Matchpercentage': 0,
                            'VoorlopigePositie': '0',
                            'Foto_Locatie': '',
                            'GepersonaliseerdeHuur': '0',
                            'IsCluster': False,
                            'EenheidSoort': '',
                            'Adres': {
                                'Straatnaam': '',
                                'Huisnummer': 0,
                                'Huisletter': '',
                                'HuisnummerToevoeging': '',
                                'Postcode': '',
                                'Woonplaats': '',
                                'Wijk': '',
                                'PublicatieId': '0',
                            },
                            'Cluster': {
                                'Naam': '',
                                'DetailSoort': '',
                                'Doelgroep': '',
                                'PrijsMinBekend': False,
                                'PrijsMin': '0',
                                'PrijsMaxBekend': False,
                                'PrijsMax': '0',
                                'WoonOppervlakteMinBekend': False,
                                'WoonVertrekkenTotOppMin': 0,
                                'WoonOppervlakteMaxBekend': False,
                                'WoonVertrekkenTotOppMax': 0,
                                'AantalEenheden': 0,
                                'AantalKamersMin': 0,
                                'AantalKamersMax': 0,
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'Eigenaar': '',
                            },
                            'Eenheid': {
                                'DetailSoort': '',
                                'Bestemming': '',
                                'AantalKamers': 0,
                                'TotaleOppervlakte': '0',
                                'WoonVertrekkenTotOpp': '0',
                                'Doelgroep': '',
                                'NettoHuurBekend': False,
                                'NettoHuur': '0',
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'EnergieLabel': '',
                                'EnergieIndex': 0,
                                'Eigenaar': '',
                                'BrutoHuurBekend': False,
                                'Brutohuur': '0',
                                'SubsidiabeleHuur': '0',
                            },
                            'PublicatieLabel': '',
                            'IsBewaard': False,
                            'IsVerborgen': False,
                            'ContractVorm': '',
                            'PublicatieOmschrijving': {
                                'Id': '0',
                                'Tekst': None,
                            },
                            'AantalReactiesOpPublicatie': '0',
                            'HeeftGereageerd': False,
                            'IsIntrekkenReactieToegestaan': False,
                            'RedenNietIntrekkenReactie': '',
                            'PositieAanbiedingsproces': '',
                            'VirtuelePositie': 0,
                            'Opleverdatum': '1900-01-01T00:00:00',
                            'HeeftLift': False,
                            'Verdieping': '',
                            'IsMetGepersonaliseerdeHuur': False,
                            'Voorziening': '',
                            'AanbiedingProcesSoort': '',
                        },
                    },
                    'PublicatieLijst_Aanbod': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'EinddatumTijd': '1900-01-01T00:00:00',
                            'PublicatieModel': '',
                            'PublicatieModule': '',
                            'PublicatieDatum': '1900-01-01T00:00:00',
                            'Matchpercentage': 0,
                            'VoorlopigePositie': '0',
                            'Foto_Locatie': '',
                            'GepersonaliseerdeHuur': '0',
                            'IsCluster': False,
                            'EenheidSoort': '',
                            'Adres': {
                                'Straatnaam': '',
                                'Huisnummer': 0,
                                'Huisletter': '',
                                'HuisnummerToevoeging': '',
                                'Postcode': '',
                                'Woonplaats': '',
                                'Wijk': '',
                                'PublicatieId': '0',
                            },
                            'Cluster': {
                                'Naam': '',
                                'DetailSoort': '',
                                'Doelgroep': '',
                                'PrijsMinBekend': False,
                                'PrijsMin': '0',
                                'PrijsMaxBekend': False,
                                'PrijsMax': '0',
                                'WoonOppervlakteMinBekend': False,
                                'WoonVertrekkenTotOppMin': 0,
                                'WoonOppervlakteMaxBekend': False,
                                'WoonVertrekkenTotOppMax': 0,
                                'AantalEenheden': 0,
                                'AantalKamersMin': 0,
                                'AantalKamersMax': 0,
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'Eigenaar': '',
                            },
                            'Eenheid': {
                                'DetailSoort': '',
                                'Bestemming': '',
                                'AantalKamers': 0,
                                'TotaleOppervlakte': '0',
                                'WoonVertrekkenTotOpp': '0',
                                'Doelgroep': '',
                                'NettoHuurBekend': False,
                                'NettoHuur': '0',
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'EnergieLabel': '',
                                'EnergieIndex': 0,
                                'Eigenaar': '',
                                'BrutoHuurBekend': False,
                                'Brutohuur': '0',
                                'SubsidiabeleHuur': '0',
                            },
                            'PublicatieLabel': '',
                            'IsBewaard': False,
                            'IsVerborgen': False,
                            'ContractVorm': '',
                            'PublicatieOmschrijving': {
                                'Id': '0',
                                'Tekst': None,
                            },
                            'AantalReactiesOpPublicatie': '0',
                            'HeeftGereageerd': False,
                            'IsIntrekkenReactieToegestaan': False,
                            'RedenNietIntrekkenReactie': '',
                            'PositieAanbiedingsproces': '',
                            'VirtuelePositie': 0,
                            'Opleverdatum': '1900-01-01T00:00:00',
                            'HeeftLift': False,
                            'Verdieping': '',
                            'IsMetGepersonaliseerdeHuur': False,
                            'Voorziening': '',
                            'AanbiedingProcesSoort': '',
                        },
                    },
                    'PublicatieLijst_Loting': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'EinddatumTijd': '1900-01-01T00:00:00',
                            'PublicatieModel': '',
                            'PublicatieModule': '',
                            'PublicatieDatum': '1900-01-01T00:00:00',
                            'Matchpercentage': 0,
                            'VoorlopigePositie': '0',
                            'Foto_Locatie': '',
                            'GepersonaliseerdeHuur': '0',
                            'IsCluster': False,
                            'EenheidSoort': '',
                            'Adres': {
                                'Straatnaam': '',
                                'Huisnummer': 0,
                                'Huisletter': '',
                                'HuisnummerToevoeging': '',
                                'Postcode': '',
                                'Woonplaats': '',
                                'Wijk': '',
                                'PublicatieId': '0',
                            },
                            'Cluster': {
                                'Naam': '',
                                'DetailSoort': '',
                                'Doelgroep': '',
                                'PrijsMinBekend': False,
                                'PrijsMin': '0',
                                'PrijsMaxBekend': False,
                                'PrijsMax': '0',
                                'WoonOppervlakteMinBekend': False,
                                'WoonVertrekkenTotOppMin': 0,
                                'WoonOppervlakteMaxBekend': False,
                                'WoonVertrekkenTotOppMax': 0,
                                'AantalEenheden': 0,
                                'AantalKamersMin': 0,
                                'AantalKamersMax': 0,
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'Eigenaar': '',
                            },
                            'Eenheid': {
                                'DetailSoort': '',
                                'Bestemming': '',
                                'AantalKamers': 0,
                                'TotaleOppervlakte': '0',
                                'WoonVertrekkenTotOpp': '0',
                                'Doelgroep': '',
                                'NettoHuurBekend': False,
                                'NettoHuur': '0',
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'EnergieLabel': '',
                                'EnergieIndex': 0,
                                'Eigenaar': '',
                                'BrutoHuurBekend': False,
                                'Brutohuur': '0',
                                'SubsidiabeleHuur': '0',
                            },
                            'PublicatieLabel': '',
                            'IsBewaard': False,
                            'IsVerborgen': False,
                            'ContractVorm': '',
                            'PublicatieOmschrijving': {
                                'Id': '0',
                                'Tekst': None,
                            },
                            'AantalReactiesOpPublicatie': '0',
                            'HeeftGereageerd': False,
                            'IsIntrekkenReactieToegestaan': False,
                            'RedenNietIntrekkenReactie': '',
                            'PositieAanbiedingsproces': '',
                            'VirtuelePositie': 0,
                            'Opleverdatum': '1900-01-01T00:00:00',
                            'HeeftLift': False,
                            'Verdieping': '',
                            'IsMetGepersonaliseerdeHuur': False,
                            'Voorziening': '',
                            'AanbiedingProcesSoort': '',
                        },
                    },
                    'PublicatieLijst_VrijeSector': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'EinddatumTijd': '1900-01-01T00:00:00',
                            'PublicatieModel': '',
                            'PublicatieModule': '',
                            'PublicatieDatum': '1900-01-01T00:00:00',
                            'Matchpercentage': 0,
                            'VoorlopigePositie': '0',
                            'Foto_Locatie': '',
                            'GepersonaliseerdeHuur': '0',
                            'IsCluster': False,
                            'EenheidSoort': '',
                            'Adres': {
                                'Straatnaam': '',
                                'Huisnummer': 0,
                                'Huisletter': '',
                                'HuisnummerToevoeging': '',
                                'Postcode': '',
                                'Woonplaats': '',
                                'Wijk': '',
                                'PublicatieId': '0',
                            },
                            'Cluster': {
                                'Naam': '',
                                'DetailSoort': '',
                                'Doelgroep': '',
                                'PrijsMinBekend': False,
                                'PrijsMin': '0',
                                'PrijsMaxBekend': False,
                                'PrijsMax': '0',
                                'WoonOppervlakteMinBekend': False,
                                'WoonVertrekkenTotOppMin': 0,
                                'WoonOppervlakteMaxBekend': False,
                                'WoonVertrekkenTotOppMax': 0,
                                'AantalEenheden': 0,
                                'AantalKamersMin': 0,
                                'AantalKamersMax': 0,
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'Eigenaar': '',
                            },
                            'Eenheid': {
                                'DetailSoort': '',
                                'Bestemming': '',
                                'AantalKamers': 0,
                                'TotaleOppervlakte': '0',
                                'WoonVertrekkenTotOpp': '0',
                                'Doelgroep': '',
                                'NettoHuurBekend': False,
                                'NettoHuur': '0',
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'EnergieLabel': '',
                                'EnergieIndex': 0,
                                'Eigenaar': '',
                                'BrutoHuurBekend': False,
                                'Brutohuur': '0',
                                'SubsidiabeleHuur': '0',
                            },
                            'PublicatieLabel': '',
                            'IsBewaard': False,
                            'IsVerborgen': False,
                            'ContractVorm': '',
                            'PublicatieOmschrijving': {
                                'Id': '0',
                                'Tekst': None,
                            },
                            'AantalReactiesOpPublicatie': '0',
                            'HeeftGereageerd': False,
                            'IsIntrekkenReactieToegestaan': False,
                            'RedenNietIntrekkenReactie': '',
                            'PositieAanbiedingsproces': '',
                            'VirtuelePositie': 0,
                            'Opleverdatum': '1900-01-01T00:00:00',
                            'HeeftLift': False,
                            'Verdieping': '',
                            'IsMetGepersonaliseerdeHuur': False,
                            'Voorziening': '',
                            'AanbiedingProcesSoort': '',
                        },
                    },
                    'PublicatieLijst_ParkerenOverig': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'EinddatumTijd': '1900-01-01T00:00:00',
                            'PublicatieModel': '',
                            'PublicatieModule': '',
                            'PublicatieDatum': '1900-01-01T00:00:00',
                            'Matchpercentage': 0,
                            'VoorlopigePositie': '0',
                            'Foto_Locatie': '',
                            'GepersonaliseerdeHuur': '0',
                            'IsCluster': False,
                            'EenheidSoort': '',
                            'Adres': {
                                'Straatnaam': '',
                                'Huisnummer': 0,
                                'Huisletter': '',
                                'HuisnummerToevoeging': '',
                                'Postcode': '',
                                'Woonplaats': '',
                                'Wijk': '',
                                'PublicatieId': '0',
                            },
                            'Cluster': {
                                'Naam': '',
                                'DetailSoort': '',
                                'Doelgroep': '',
                                'PrijsMinBekend': False,
                                'PrijsMin': '0',
                                'PrijsMaxBekend': False,
                                'PrijsMax': '0',
                                'WoonOppervlakteMinBekend': False,
                                'WoonVertrekkenTotOppMin': 0,
                                'WoonOppervlakteMaxBekend': False,
                                'WoonVertrekkenTotOppMax': 0,
                                'AantalEenheden': 0,
                                'AantalKamersMin': 0,
                                'AantalKamersMax': 0,
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'Eigenaar': '',
                            },
                            'Eenheid': {
                                'DetailSoort': '',
                                'Bestemming': '',
                                'AantalKamers': 0,
                                'TotaleOppervlakte': '0',
                                'WoonVertrekkenTotOpp': '0',
                                'Doelgroep': '',
                                'NettoHuurBekend': False,
                                'NettoHuur': '0',
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'EnergieLabel': '',
                                'EnergieIndex': 0,
                                'Eigenaar': '',
                                'BrutoHuurBekend': False,
                                'Brutohuur': '0',
                                'SubsidiabeleHuur': '0',
                            },
                            'PublicatieLabel': '',
                            'IsBewaard': False,
                            'IsVerborgen': False,
                            'ContractVorm': '',
                            'PublicatieOmschrijving': {
                                'Id': '0',
                                'Tekst': None,
                            },
                            'AantalReactiesOpPublicatie': '0',
                            'HeeftGereageerd': False,
                            'IsIntrekkenReactieToegestaan': False,
                            'RedenNietIntrekkenReactie': '',
                            'PositieAanbiedingsproces': '',
                            'VirtuelePositie': 0,
                            'Opleverdatum': '1900-01-01T00:00:00',
                            'HeeftLift': False,
                            'Verdieping': '',
                            'IsMetGepersonaliseerdeHuur': False,
                            'Voorziening': '',
                            'AanbiedingProcesSoort': '',
                        },
                    },
                    'PublicatieLijst_Koop': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'EinddatumTijd': '1900-01-01T00:00:00',
                            'PublicatieModel': '',
                            'PublicatieModule': '',
                            'PublicatieDatum': '1900-01-01T00:00:00',
                            'Matchpercentage': 0,
                            'VoorlopigePositie': '0',
                            'Foto_Locatie': '',
                            'GepersonaliseerdeHuur': '0',
                            'IsCluster': False,
                            'EenheidSoort': '',
                            'Adres': {
                                'Straatnaam': '',
                                'Huisnummer': 0,
                                'Huisletter': '',
                                'HuisnummerToevoeging': '',
                                'Postcode': '',
                                'Woonplaats': '',
                                'Wijk': '',
                                'PublicatieId': '0',
                            },
                            'Cluster': {
                                'Naam': '',
                                'DetailSoort': '',
                                'Doelgroep': '',
                                'PrijsMinBekend': False,
                                'PrijsMin': '0',
                                'PrijsMaxBekend': False,
                                'PrijsMax': '0',
                                'WoonOppervlakteMinBekend': False,
                                'WoonVertrekkenTotOppMin': 0,
                                'WoonOppervlakteMaxBekend': False,
                                'WoonVertrekkenTotOppMax': 0,
                                'AantalEenheden': 0,
                                'AantalKamersMin': 0,
                                'AantalKamersMax': 0,
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'Eigenaar': '',
                            },
                            'Eenheid': {
                                'DetailSoort': '',
                                'Bestemming': '',
                                'AantalKamers': 0,
                                'TotaleOppervlakte': '0',
                                'WoonVertrekkenTotOpp': '0',
                                'Doelgroep': '',
                                'NettoHuurBekend': False,
                                'NettoHuur': '0',
                                'Lengtegraad': '0',
                                'Breedtegraad': '0',
                                'Toegankelijkheid': '',
                                'Toegankelijkheidstag': '',
                                'PublicatieId': '0',
                                'SoortBouw': '',
                                'EnergieLabel': '',
                                'EnergieIndex': 0,
                                'Eigenaar': '',
                                'BrutoHuurBekend': False,
                                'Brutohuur': '0',
                                'SubsidiabeleHuur': '0',
                            },
                            'PublicatieLabel': '',
                            'IsBewaard': False,
                            'IsVerborgen': False,
                            'ContractVorm': '',
                            'PublicatieOmschrijving': {
                                'Id': '0',
                                'Tekst': None,
                            },
                            'AantalReactiesOpPublicatie': '0',
                            'HeeftGereageerd': False,
                            'IsIntrekkenReactieToegestaan': False,
                            'RedenNietIntrekkenReactie': '',
                            'PositieAanbiedingsproces': '',
                            'VirtuelePositie': 0,
                            'Opleverdatum': '1900-01-01T00:00:00',
                            'HeeftLift': False,
                            'Verdieping': '',
                            'IsMetGepersonaliseerdeHuur': False,
                            'Voorziening': '',
                            'AanbiedingProcesSoort': '',
                        },
                    },
                    'PublicatieLijst_HasAanbod': True,
                    'PublicatieLijst_Base_TeWeinigAanbod': False,
                    'PublicatieLijst_VerborgenItems': 0,
                    'HuidigePublicatieId': '0',
                    '_huidigePublicatieIdInDataFetchStatus': 1,
                    'woonplaats': '',
                    '_woonplaatsInDataFetchStatus': 1,
                    'soort': '',
                    '_soortInDataFetchStatus': 1,
                    'type': '',
                    '_typeInDataFetchStatus': 1,
                    'kamers': '',
                    '_kamersInDataFetchStatus': 1,
                    'doelgroep': '',
                    '_doelgroepInDataFetchStatus': 1,
                    'contractvorm': '',
                    '_contractvormInDataFetchStatus': 1,
                    'toegankelijkheid': '',
                    '_toegankelijkheidInDataFetchStatus': 1,
                    'aanbieder': '',
                    '_aanbiederInDataFetchStatus': 1,
                },
            },
            'clientVariables': {
                'Voorkeuren_LaatsteLogin': '1900-01-01T00:00:00',
                'EnableDarkMode': False,
                'HoofdAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'MK_Tijd': '0',
                'BerichtVerwijderenActief': False,
                'ClientLogEnabled': False,
                'IsVerbergenVraagNietMeer': False,
                'MoetInschrijfKostenBetalen': False,
                'SamenwerkingsverbandId': '2',
                'IsIngelogdMetNumeriekeGebruikersnaam': False,
                'ProfielPanelenIncompleet': '',
                'MFA_ClientSettings': '',
                'OpleidingWRBOmschrijving': '',
                'Weergave_Filters': '[]',
                'MK_Timeout': 10,
                'IsUitgebreidZoeken': False,
                'CacheVariant': 1,
                'ZoekAanbod': '',
                'RegelingWRBNaam': '',
                'QiiInProfiel': False,
                'MFA_Request': '',
                'LastURL': '',
                'IsVerbergKaart': False,
                'InschrijvenVoortzettenMogelijk': False,
                'RegelingIsCompleet': False,
                'MedeAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'IsWeergavePuntenteller': False,
                'MK_Gebruiker': '',
                'SamenwerkingsverbandNaam': 'Regio Amsterdam',
                'Weergave_HeeftFilters': False,
                'SamenwerkingsverbandCode': 'SRA',
                'MFA_Sessie': '',
                'IsMK': False,
                'OpleidingWRBNaam': '',
                'Weergave_SorteringIsAflopend': True,
                'OpleidingIsCompleet': False,
                'Weergave_GebruikWoonwensFilter': True,
                'MK_Token': '',
                'MaandenHistorie': -36,
                'QiiKeuzeRelatiegroepStatusCodeId': 0,
                'MK_Woningzoekende': '',
                'IsWeergaveEinddatum': True,
                'CheckProfielPanelenVoorPopup': True,
                'ToonNieuweProfielBerichten': False,
                'Weergave_HeeftSidebar': False,
                'Weergave_Sortering': 6,
                'RegelingWRBOmschrijving': '',
                'Username': '',
                'MK_Email': '',
                'MFA_RequestId': '0',
                'Weergave_HeeftKaart': True,
            },
        }

        name_headers = {
            'Accept': 'application/json',
            'X-CSRFToken': f'{csrf_token}',
            'Content-Type': 'application/json; charset=UTF-8',
            'Origin': 'https://amsterdam.mijndak.nl',
            'Referer': 'https://amsterdam.mijndak.nl/Woningaanbod',
        }

        name_payload = {
            'versionInfo': {
                'moduleVersion': 'gc5UrXD2cJlgmpzXRSB5nQ',
                'apiVersion': 'LjHBmML6NyJfL7H5ZGerpA',
            },
            'viewName': 'Overzicht.Woningaanbod',
            'screenData': {
                'variables': {
                    'Origin': 'https://amsterdam.mijndak.nl',
                },
            },
            'inputParameters': {},
            'clientVariables': {
                'Voorkeuren_LaatsteLogin': '1900-01-01T00:00:00',
                'EnableDarkMode': False,
                'HoofdAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'MK_Tijd': '0',
                'BerichtVerwijderenActief': False,
                'ClientLogEnabled': False,
                'IsVerbergenVraagNietMeer': False,
                'MoetInschrijfKostenBetalen': False,
                'SamenwerkingsverbandId': '2',
                'IsIngelogdMetNumeriekeGebruikersnaam': False,
                'ProfielPanelenIncompleet': '',
                'MFA_ClientSettings': '',
                'OpleidingWRBOmschrijving': '',
                'Weergave_Filters': '[]',
                'MK_Timeout': 10,
                'IsUitgebreidZoeken': False,
                'CacheVariant': 1,
                'ZoekAanbod': '',
                'RegelingWRBNaam': '',
                'QiiInProfiel': False,
                'MFA_Request': '',
                'LastURL': '',
                'IsVerbergKaart': False,
                'InschrijvenVoortzettenMogelijk': False,
                'RegelingIsCompleet': False,
                'MedeAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'IsWeergavePuntenteller': False,
                'MK_Gebruiker': '',
                'SamenwerkingsverbandNaam': 'Regio Amsterdam',
                'Weergave_HeeftFilters': False,
                'SamenwerkingsverbandCode': 'SRA',
                'MFA_Sessie': '',
                'IsMK': False,
                'OpleidingWRBNaam': '',
                'Weergave_SorteringIsAflopend': True,
                'OpleidingIsCompleet': False,
                'Weergave_GebruikWoonwensFilter': True,
                'MK_Token': '',
                'MaandenHistorie': -36,
                'QiiKeuzeRelatiegroepStatusCodeId': 0,
                'MK_Woningzoekende': '',
                'IsWeergaveEinddatum': True,
                'CheckProfielPanelenVoorPopup': True,
                'ToonNieuweProfielBerichten': False,
                'Weergave_HeeftSidebar': False,
                'Weergave_Sortering': 6,
                'RegelingWRBOmschrijving': '',
                'Username': '',
                'MK_Email': '',
                'MFA_RequestId': '0',
                'Weergave_HeeftKaart': True,
            },
        }

        publication_headers = {
            'Accept': 'application/json',
            'X-CSRFToken': f'{csrf_token}',
            'Content-Type': 'application/json; charset=UTF-8',
            'Origin': 'https://amsterdam.mijndak.nl',
            'Referer': f"https://amsterdam.mijndak.nl/HuisDetails?PublicatieId={publication_id}",
        }

        publication_payload = {
            'versionInfo': {
                'moduleVersion': 'gc5UrXD2cJlgmpzXRSB5nQ',
                'apiVersion': 'l0d9h5zG1Zw7MaPsx8obPw',
            },
            'viewName': 'HuisDetails.HuisDetails',
            'screenData': {
                'variables': {
                    'ActiveScreenBestaat': True,
                    'HeightVoorImageLocal': 0,
                    'DeviceType': 2,
                    'IsVoorkeurDoorgevenSucces': False,
                    'IsLaden': False,
                    'PublicatieIdLocal': publication_id,
                    'IsPublicatieVerbergen': False,
                    'IsVerbergenFetched': False,
                    'PublicatieId': publication_id,
                    '_publicatieIdInDataFetchStatus': 1,
                    'IsVanPassend': True,
                    '_isVanPassendInDataFetchStatus': 1,
                    'IsVanReacties': False,
                    '_isVanReactiesInDataFetchStatus': 1,
                    'IsVanFavorieten': False,
                    '_isVanFavorietenInDataFetchStatus': 1,
                    'Tab': -1,
                    '_tabInDataFetchStatus': 1,
                    'GetInschrijvingenByUserId': {
                        'List': {
                            'List': [],
                            'EmptyListItem': {
                                'Inschrijving': {
                                    'Id': '0',
                                    'UserId': 0,
                                    'NatuurlijkPersoonId': '0',
                                    'SamenwerkingsverbandId': '0',
                                    'NatuurlijkPersoon': '',
                                    'Samenwerkingsverband': '',
                                    'IsActiefSamenwerkingsverband': True,
                                    'VerloopDatum': '1900-01-01',
                                    'ProductCode': '',
                                },
                            },
                        },
                        'Count': '-1',
                        'DataFetchStatus': 1,
                    },
                    'GetPublicatie': {
                        'List': {
                            'List': [],
                            'EmptyListItem': {
                                'Publicatie': {
                                    'PublicatieId': '0',
                                    'SamenwerkingsverbandId': '0',
                                    'AantalEenhedenBeschikbaar': 0,
                                    'BeginDatumTijd': '1900-01-01T00:00:00',
                                    'EindDatumTijd': '1900-01-01T00:00:00',
                                    'ContractVorm': '',
                                    'SpelregelSet': '',
                                    'Looptijd': '',
                                    'OpleverDatum': '1900-01-01',
                                    'ContractEindDatum': '1900-01-01',
                                    'PublicatieLabel': '',
                                    'PublicatieStatus': '',
                                    'PublicatieDetailStatus': '',
                                    'MaxAantalAanbiedingsronden': 0,
                                    'MetGepersonaliseerdeHuur': False,
                                    'AdvertentieURL': '',
                                    'PublicatieDetailModel': '',
                                    'PublicatieIntakevorm': '',
                                    'PublicatieModel': '',
                                    'PublicatieModule': '',
                                    'Oplevering': '',
                                    'ReactieURL': '',
                                    'EmailAdresReactie': '',
                                    'EmailAdresAanbieding': '',
                                    'AfrondenOpEindDatum': False,
                                    'AanbiedingProcesSoort': '',
                                    'LaatstGesynchroniseerdOp': '1900-01-01T00:00:00',
                                    'IsPassendVoorIedereen': False,
                                    'HeeftKandidatenLijst': False,
                                    'FirstSync': '1900-01-01T00:00:00',
                                },
                                'PublicatieBewaard': {
                                    'Id': '0',
                                    'PublicatieId': '0',
                                    'SamenwerkingsverbandId': '0',
                                    'NatuurlijkPersoonId': '0',
                                    'LaatstBijgewerkt': '1900-01-01T00:00:00',
                                    'IsActief': True,
                                },
                                'Eenheid': {
                                    'PublicatieId': '0',
                                    'Code': '',
                                    'Naam': '',
                                    'Omschrijving': '',
                                    'EenheidSoort': '',
                                    'DetailSoort': '',
                                    'EenheidStatus': '',
                                    'EenheidDetailStatus': '',
                                    'Eigenaar': '',
                                    'EtageBekend': False,
                                    'Etage': 0,
                                    'InExploitatieDatum': '1900-01-01',
                                    'InExploitatieReden': '',
                                    'UitExploitatieDatum': '1900-01-01',
                                    'UitExploitatieReden': '',
                                    'AantalKamers': 0,
                                    'TotaleOppervlakte': '0',
                                    'TotaleInhoud': 0,
                                    'BewoonbareVertrekkenTotInh': '0',
                                    'WoonVertrekkenTotOpp': '0',
                                    'WoonVertrekInhoud': '0',
                                    'OverigeVertrekkenTotOppervla': '0',
                                    'PerceelOppervlakte': 0,
                                    'Bestemming': '',
                                    'Doelgroep': '',
                                    'AanvullendeDoelgroep': '',
                                    'Woonvorm': '',
                                    'IsZelfstandig': False,
                                    'HeeftLift': False,
                                    'ZorgfacaliteitOmschrijving': '',
                                    'Kwaliteitsniveau': '',
                                    'OpleverDatum': '1900-01-01',
                                    'BrutoHuurBekend': False,
                                    'BrutoHuur': '0',
                                    'NettoHuurBekend': False,
                                    'NettoHuur': '0',
                                    'SubsidiabeleHuur': '0',
                                    'Streefhuur': '0',
                                    'Vraagprijs': '0',
                                    'VraagprijsBekend': False,
                                    'BeschikbaarVoorVerkoop': False,
                                    'Situering': '',
                                    'MaatschappelijkLabel': '',
                                    'IsNieuwbouw': False,
                                    'EnergieLabel': '',
                                    'EnergieIndex': '0',
                                    'Prijsconditie': '',
                                    'Bouwnummer': '',
                                    'Lengtegraad': '0',
                                    'Breedtegraad': '0',
                                    'Toegankelijkheid': '',
                                    'Toegankelijkheidstag': '',
                                    'EenheidSoortId': '0',
                                    'DetailSoortId': '0',
                                    'ToegankelijkheidId': '0',
                                    'SoortBouw': '',
                                },
                                'PublicatieVerborgen': {
                                    'Id': '0',
                                    'PublicatieId': '0',
                                    'SamenwerkingsverbandId': '0',
                                    'NatuurlijkPersoonId': '0',
                                    'LaatstBijgewerkt': '1900-01-01T00:00:00',
                                    'IsActief': True,
                                },
                                'Adres': {
                                    'PublicatieId': '0',
                                    'Straatnaam': '',
                                    'Huisnummer': 0,
                                    'Huisletter': '',
                                    'HuisnummerToevoeging': '',
                                    'Postcode': '',
                                    'Gemeente': '',
                                    'Woonplaats': '',
                                    'Wijk': '',
                                    'Buurt': '',
                                    'GemeenteId': '0',
                                    'WoonplaatsId': '0',
                                    'WijkId': '0',
                                    'BuurtId': '0',
                                    'HuisnummerTot': 0,
                                },
                                'Cluster': {
                                    'PublicatieId': '0',
                                    'Code': '',
                                    'Naam': '',
                                    'BasisPublicatieTekst': None,
                                    'Bestemming': '',
                                    'Gemeente': '',
                                    'Stadsdeel': '',
                                    'Woonplaats': '',
                                    'Wijk': '',
                                    'Buurt': '',
                                    'EenheidStatus': '',
                                    'Woonvorm': '',
                                    'HeeftLift': False,
                                    'Doelgroep': '',
                                    'AanvullendeDoelgroep': '',
                                    'EenheidSoort': '',
                                    'DetailSoort': '',
                                    'Eigenaar': '',
                                    'Einddatum': '1900-01-01T00:00:00',
                                    'PrijsMinBekend': False,
                                    'PrijsMin': '0',
                                    'PrijsMaxBekend': False,
                                    'PrijsMax': '0',
                                    'WoonOppervlakteMinBekend': False,
                                    'WoonVertrekkenTotOppMin': 0,
                                    'WoonOppervlakteMaxBekend': False,
                                    'WoonVertrekkenTotOppMax': 0,
                                    'EtageMinBekend': False,
                                    'EtageMin': 0,
                                    'EtageMaxBekend': False,
                                    'EtageMax': 0,
                                    'AantalEenheden': 0,
                                    'AantalKamersMin': 0,
                                    'AantalKamersMax': 0,
                                    'IsZelfstandig': False,
                                    'Lengtegraad': '0',
                                    'Breedtegraad': '0',
                                    'Toegankelijkheid': '',
                                    'Toegankelijkheidstag': '',
                                    'EenheidSoortId': '0',
                                    'DetailSoortId': '0',
                                    'WoonplaatsId': '0',
                                    'ToegankelijkheidId': '0',
                                    'GemeenteId': '0',
                                    'WijkId': '0',
                                    'BuurtId': '0',
                                    'Postcode': '',
                                    'SoortBouw': '',
                                    'SubServicekostenBekend': False,
                                    'SubServicekostenMin': '0',
                                    'SubServicekostenMax': '0',
                                    'NonSubServicekostenBekend': False,
                                    'NonSubServicekostenMin': '0',
                                    'NonSubServicekostenMax': '0',
                                    'Opleverdatum': '1900-01-01',
                                    'Energielabel': '',
                                },
                            },
                        },
                        'Count': '0',
                        'DataFetchStatus': 0,
                    },
                    'GetInformatieBijInschrijving': {
                        'PublicatieKandidaatSorteerTekst': {
                            'List': [],
                            'EmptyListItem': {
                                'Id': '0',
                                'VolgordeNummer': 0,
                                'OmschrijvingWoonPortaal': '',
                                'Waarde': False,
                                'NatuurlijkPersoonId': '0',
                                'PublicatieId': '0',
                            },
                        },
                        'PublicatieKandidaat': {
                            'Id': '0',
                            'NatuurlijkPersoonId': '0',
                            'PublicatieId': '0',
                            'Positie': 0,
                            'Huurtoeslag': '0',
                            'GepersonaliseerdeHuur': '0',
                            'KandidaatStatus': '',
                            'KandidaatDetailStatus': '',
                            'SorteerTekst': '',
                            'GesynchroniseerdOp': '1900-01-01T00:00:00',
                        },
                        'MatchPercentage': 0,
                        'WoonWensList': {
                            'List': [],
                            'EmptyListItem': {
                                'Label': '',
                                'IsMatch': False,
                            },
                        },
                        'IsPassendVoorKandidaat': False,
                        'DataFetchStatus': 0,
                    },
                },
            },
            'inputParameters': {
                'StartIndex': 0,
                'MaxRecords': 1,
            },
            'clientVariables': {
                'Voorkeuren_LaatsteLogin': '1900-01-01T00:00:00',
                'EnableDarkMode': False,
                'HoofdAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'MK_Tijd': '0',
                'BerichtVerwijderenActief': False,
                'ClientLogEnabled': False,
                'IsVerbergenVraagNietMeer': False,
                'MoetInschrijfKostenBetalen': False,
                'SamenwerkingsverbandId': '2',
                'IsIngelogdMetNumeriekeGebruikersnaam': False,
                'ProfielPanelenIncompleet': '',
                'MFA_ClientSettings': '',
                'OpleidingWRBOmschrijving': '',
                'Weergave_Filters': '[]',
                'MK_Timeout': 10,
                'IsUitgebreidZoeken': False,
                'CacheVariant': 1,
                'ZoekAanbod': '',
                'RegelingWRBNaam': '',
                'QiiInProfiel': False,
                'MFA_Request': '',
                'LastURL': '',
                'IsVerbergKaart': False,
                'InschrijvenVoortzettenMogelijk': False,
                'RegelingIsCompleet': False,
                'MedeAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'IsWeergavePuntenteller': False,
                'MK_Gebruiker': '',
                'SamenwerkingsverbandNaam': 'Regio Amsterdam',
                'Weergave_HeeftFilters': False,
                'SamenwerkingsverbandCode': 'SRA',
                'MFA_Sessie': '',
                'IsMK': False,
                'OpleidingWRBNaam': '',
                'Weergave_SorteringIsAflopend': True,
                'OpleidingIsCompleet': False,
                'Weergave_GebruikWoonwensFilter': True,
                'MK_Token': '',
                'MaandenHistorie': -36,
                'QiiKeuzeRelatiegroepStatusCodeId': 0,
                'MK_Woningzoekende': '',
                'IsWeergaveEinddatum': True,
                'CheckProfielPanelenVoorPopup': True,
                'ToonNieuweProfielBerichten': False,
                'Weergave_HeeftSidebar': False,
                'Weergave_Sortering': 6,
                'RegelingWRBOmschrijving': '',
                'Username': '',
                'MK_Email': '',
                'MFA_RequestId': '0',
                'Weergave_HeeftKaart': True,
            },
        }

        detail_headers = {
            'Accept': 'application/json',
            'X-CSRFToken': f'{csrf_token}',
            'Content-Type': 'application/json; charset=UTF-8',
            'Origin': 'https://amsterdam.mijndak.nl',
            'Referer': f'https://amsterdam.mijndak.nl/HuisDetails?PublicatieId={publication_id}',
        }

        detail_payload = {
            'versionInfo': {
                'moduleVersion': 'gc5UrXD2cJlgmpzXRSB5nQ',
                'apiVersion': '+97OLEczQGGczV97ite8Ng',
            },
            'viewName': 'HuisDetails.HuisDetails',
            'screenData': {
                'variables': {
                    'VertrekkenLijst': {
                        'List': [],
                        'EmptyListItem': {
                            'RuimteSoort': '',
                            'Naam': '',
                            'Oppervlakte': '',
                            'Inhoud': '',
                        },
                    },
                    'ServiceKostenLijst': {
                        'List': [],
                        'EmptyListItem': {
                            'Naam': '',
                            'Omschrijving': '',
                            'Bedrag': '0',
                        },
                    },
                    'VerbruiksKostenLijst': {
                        'List': [],
                        'EmptyListItem': {
                            'Naam': '',
                            'Omschrijving': '',
                            'Bedrag': '0',
                        },
                    },
                    'VoorzieningenLijst': {
                        'List': [],
                        'EmptyListItem': {
                            'Groep': '',
                            'Omschrijving': '',
                        },
                    },
                    'VerbruiksKosten': '0',
                    'ServiceKosten': '0',
                    'Voorwaarden': '',
                    'Omschrijving': '',
                    'IsServicekostenUitgeklapt': False,
                    'IsVerbruikskostenUitgeklapt': False,
                    'DeviceType': 0,
                    'BetaalbaarheidscoreTekst': {
                        'List': [
                            'De betaalbaarheid van deze woning voor jou scoort 5 sterren! Deze woning past heel goed binnen uw budget, omdat de woonlasten laag zijn. Hierdoor is het mogelijk om uw andere noodzakelijke uitgaven, zoals  boodschappen, kleding of onverwachte rekeningen) te blijven doen. Ook is er financiële ruimte voor leuke dingen.',
                            'De betaalbaarheid van deze woning voor jou scoort 4 sterren. Deze woning past goed binnen uw budget. Bezuinigen op andere uitgaven is niet per se nodig, behalve  als u in de toekomst grote uitgaven verwacht.',
                            'De betaalbaarheid van deze woning voor jou scoort 3 sterren. Deze woning past binnen uw budget, maar wij adviseren u op zoek te gaan naar een andere woning die nog beter bij uw budget past. Voor deze woning is het hebben van spaargeld voor onverwachte of grote uitgaven, zoals een reparatie aan de auto of een dure tandartsrekening, aan te raden. U moet waarschijnlijk bezuinigen op andere uitgaven.',
                            'De betaalbaarheid van deze woning voor jou scoort maar 2 sterren. Wij raden u aan om op zoek gaan naar een andere woning die beter binnen uw budget past. De woonlasten van deze woning zijn hoog. Deze woonlasten kunt u alleen met veel moeite opbrengen. Voor onverwachte kosten of leuke dingen zal niet tot nauwelijks financiële ruimte zijn.',
                            'De betaalbaarheid van deze woning voor jou scoort maar 1 ster. Wij raden u aan om op zoek gaan naar een andere woning die beter binnen uw budget past. De woonlasten van deze woning zijn heel hoog. Hierdoor is het bijna onmogelijk om uw andere noodzakelijke uitgaven (zoals  boodschappen, kleding of onverwachte rekeningen) te doen. Voor leuke dingen is al helemaal geen financiële ruimte meer.',
                            'Wij kunnen niet bepalen of deze woning betaalbaar is voor u.',
                        ],
                    },
                    'Videos': {
                        'List': [],
                        'EmptyListItem': {
                            'Soort': '',
                            'URL': '',
                            'Titel': '',
                        },
                    },
                    'Bestanden': {
                        'List': [],
                        'EmptyListItem': {
                            'Soort': '',
                            'URL': '',
                            'Titel': '',
                        },
                    },
                    'ToonBerekeningKnop': False,
                    'ToonBerekeningResult': False,
                    'ToonLinkBelastingdienst': False,
                    'ToonLinkBelastingdienstNaFout': False,
                    'Publicatie': {
                        'Publicatie': {
                            'PublicatieId': publication_id,
                            'SamenwerkingsverbandId': '2',
                            'AantalEenhedenBeschikbaar': 0,
                            'BeginDatumTijd': '2025-08-04T22:01:00.000Z',
                            'EindDatumTijd': '2025-08-11T21:59:00.000Z',
                            'ContractVorm': 'Jongerencontract',
                            'SpelregelSet': '#Situatiepunten Jongerenwoning',
                            'Looptijd': '',
                            'OpleverDatum': '2025-08-19',
                            'ContractEindDatum': '1900-01-01',
                            'PublicatieLabel': 'Met situatiepunten~Jongerenwoning',
                            'PublicatieStatus': 'Gepubliceerd',
                            'PublicatieDetailStatus': '',
                            'MaxAantalAanbiedingsronden': 0,
                            'MetGepersonaliseerdeHuur': False,
                            'AdvertentieURL': 'https://amsterdam.mijndak.nl/eenheiddetails/317258',
                            'PublicatieDetailModel': '',
                            'PublicatieIntakevorm': '',
                            'PublicatieModel': 'Aanbodmodel',
                            'PublicatieModule': 'Sociale huur',
                            'Oplevering': '',
                            'ReactieURL': 'https://amsterdam.mijndak.nl/eenheiddetails/Reageren/317258',
                            'EmailAdresReactie': '',
                            'EmailAdresAanbieding': 'MailWoningnet@dekey.nl',
                            'AfrondenOpEindDatum': False,
                            'AanbiedingProcesSoort': 'Standaard aanbiedingsproces',
                            'LaatstGesynchroniseerdOp': '2025-08-04T23:29:06.000Z',
                            'IsPassendVoorIedereen': False,
                            'HeeftKandidatenLijst': True,
                            'FirstSync': '2025-08-04T23:26:48.000Z',
                        },
                        'Adres': {
                            'PublicatieId': publication_id,
                            'Straatnaam': 'Gillis van Ledenberchstraat',
                            'Huisnummer': 131,
                            'Huisletter': '',
                            'HuisnummerToevoeging': '2',
                            'Postcode': '1052VE',
                            'Gemeente': 'Amsterdam',
                            'Woonplaats': 'Amsterdam',
                            'Wijk': 'Frederik Hendrikbuurt (West)',
                            'Buurt': 'Frederik Hendrikbuurt-Zuidoost',
                            'GemeenteId': '131',
                            'WoonplaatsId': '68',
                            'WijkId': '3941',
                            'BuurtId': '17283',
                            'HuisnummerTot': 0,
                        },
                        'Eenheid': {
                            'PublicatieId': publication_id,
                            'Code': 'VHE20201000369',
                            'Naam': '',
                            'Omschrijving': '',
                            'EenheidSoort': 'Woonruimte',
                            'DetailSoort': 'Portiekwoning',
                            'EenheidStatus': 'Leegstand',
                            'EenheidDetailStatus': '',
                            'Eigenaar': 'Lieven de Key Amsterdam',
                            'EtageBekend': True,
                            'Etage': 2,
                            'InExploitatieDatum': '1900-01-01',
                            'InExploitatieReden': '',
                            'UitExploitatieDatum': '1900-01-01',
                            'UitExploitatieReden': '',
                            'AantalKamers': 2,
                            'TotaleOppervlakte': '20.98',
                            'TotaleInhoud': 0,
                            'BewoonbareVertrekkenTotInh': '0',
                            'WoonVertrekkenTotOpp': '38.98',
                            'WoonVertrekInhoud': '0',
                            'OverigeVertrekkenTotOppervla': '0',
                            'PerceelOppervlakte': 0,
                            'Bestemming': 'Huur',
                            'Doelgroep': 'Jongeren',
                            'AanvullendeDoelgroep': '',
                            'Woonvorm': '',
                            'IsZelfstandig': True,
                            'HeeftLift': False,
                            'ZorgfacaliteitOmschrijving': '',
                            'Kwaliteitsniveau': '',
                            'OpleverDatum': '1898-12-31',
                            'BrutoHuurBekend': True,
                            'BrutoHuur': '821.22',
                            'NettoHuurBekend': True,
                            'NettoHuur': '813.91',
                            'SubsidiabeleHuur': '818.66',
                            'Streefhuur': '0',
                            'Vraagprijs': '0',
                            'VraagprijsBekend': False,
                            'BeschikbaarVoorVerkoop': False,
                            'Situering': '',
                            'MaatschappelijkLabel': '',
                            'IsNieuwbouw': False,
                            'EnergieLabel': 'C',
                            'EnergieIndex': '1.58',
                            'Prijsconditie': '',
                            'Bouwnummer': '',
                            'Lengtegraad': '4.87137751',
                            'Breedtegraad': '52.37518576',
                            'Toegankelijkheid': 'Woning zonder bijzondere toegankelijkheid',
                            'Toegankelijkheidstag': 'ZON',
                            'EenheidSoortId': '2',
                            'DetailSoortId': '46',
                            'ToegankelijkheidId': '129',
                            'SoortBouw': 'Bestaande bouw',
                        },
                        'Cluster': {
                            'PublicatieId': '0',
                            'Code': '',
                            'Naam': '',
                            'BasisPublicatieTekst': None,
                            'Bestemming': '',
                            'Gemeente': '',
                            'Stadsdeel': '',
                            'Woonplaats': '',
                            'Wijk': '',
                            'Buurt': '',
                            'EenheidStatus': '',
                            'Woonvorm': '',
                            'HeeftLift': False,
                            'Doelgroep': '',
                            'AanvullendeDoelgroep': '',
                            'EenheidSoort': '',
                            'DetailSoort': '',
                            'Eigenaar': '',
                            'Einddatum': '1900-01-01T00:00:00',
                            'PrijsMinBekend': False,
                            'PrijsMin': '0',
                            'PrijsMaxBekend': False,
                            'PrijsMax': '0',
                            'WoonOppervlakteMinBekend': False,
                            'WoonVertrekkenTotOppMin': 0,
                            'WoonOppervlakteMaxBekend': False,
                            'WoonVertrekkenTotOppMax': 0,
                            'EtageMinBekend': False,
                            'EtageMin': 0,
                            'EtageMaxBekend': False,
                            'EtageMax': 0,
                            'AantalEenheden': 0,
                            'AantalKamersMin': 0,
                            'AantalKamersMax': 0,
                            'IsZelfstandig': False,
                            'Lengtegraad': '0',
                            'Breedtegraad': '0',
                            'Toegankelijkheid': '',
                            'Toegankelijkheidstag': '',
                            'EenheidSoortId': '0',
                            'DetailSoortId': '0',
                            'WoonplaatsId': '0',
                            'ToegankelijkheidId': '0',
                            'GemeenteId': '0',
                            'WijkId': '0',
                            'BuurtId': '0',
                            'Postcode': '',
                            'SoortBouw': '',
                            'SubServicekostenBekend': False,
                            'SubServicekostenMin': '0',
                            'SubServicekostenMax': '0',
                            'NonSubServicekostenBekend': False,
                            'NonSubServicekostenMin': '0',
                            'NonSubServicekostenMax': '0',
                            'Opleverdatum': '1900-01-01',
                            'Energielabel': '',
                        },
                        'Vestiging': {
                            'LogoURL': '',
                            'Naam': 'Lieven de Key Amsterdam',
                            'Logo': 'iVBORw0KGgoAAAANSUhEUgAAAPoAAADKCAMAAAC7SK2iAAAAeFBMVEX///8AAADOzs6NjY3d3d35+flCQkI4ODh5eXnt7e0rKyvKysqlpaX19fW2trZMTEzk5ORkZGTe3t6enp6rq6u7u7uhoaHBwcGVlZUUFBTu7u5sbGx/f38lJSUaGhpcXFxfX180NDRQUFCGhoZ9fX0eHh5ycnI/Pz/6VjHYAAAF0UlEQVR4nO2ZaZuqOBCFCbIIqLjjbqtX/f//cKzKQoEo3aPTd57u835pDEVSJ6lUCtrzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgN9A0NnH8Wi+KhvGf9GbbyS5KkPXtMRKfXzT4NfjMX9uMd7G8dn9KtI4jpf+ewb3VckupJYBXb6p9zZoqOcWgTTJ2M3iPWMnWvR6z38O1DSlq+w93bfxNen+O5V7OXU2pasNXfVuF+Ht7/ZN3bfxJela+exNQw+dcs872UHC6eBN3bfyFel8pd7m2lyuMPX8zbn9C9LfrNzr3nrryB8N4dTvf6KjZqPHj5o7Ven91b2hlc7xaQOUCRusv8DI7G9moWc1VMvlwTStOimNGC/Y04taqoV7dnr7tdZXnDF2m8DcuS7Vn9tJwa2R9NbQi+jOsahIH+hMe6mdLUZ6XXnNenbzxS1hpnj8r0g3q05pLi0nwzDxTJ5xz8bmIChKo5G7E/Nt5lxbncyZ56X0oOwkr4SKlq4PIudpsHTWEVsPZPTSAF2vjYp06mkope+VYG0s7Kokxu2eNDq7SYlFa2XIgbhxtHcL2YmSc8XSQ26e308ekbwu3WZ4J71DDZcgDAM++Ca6xYbSRI/GkRBlfW84ZzFWOj3g+9ODkk55NnL/ZIHfKSeGG9PZykum5QQK6Wczvpj0rbPevSydldtzPbX+FGKeQ91kHiV3bucBhd5Gt6zsAyw9L0eQy85l85Avw4OVTllhbwxSsRqe2AlOuXcU1gd95wXpK1HNWem01CdreNJDxG42xtqqsE/ZMY9Wum2k6zJ1sRJ7goZG+ljay+kV0kvlwwbrF6TrNKJreCudWlzGSfQ6UoTpXNbRT16UPBCNUyTdnQRkUWZmemztfi30AwtpzyEwfCJ90mD9L6SvpfSLbjPSuWnRsWgnQzfjZmJ2NIy1WVCwBlq6W+hexdOjkkW4WTMKubXrJKqYuIB3fXzQ9DvrnOf+Jen7ReJVpMtXOoOnw4QqKt/st3ujTEt3WbriFU9VuaQmTNK7TsowYelbue731r1XpEuM9OxuBJJOe5sS2B+zNA+lu61Sla5U5ezSvS7vOqlJ10lhUs7efyud1vUQ+IJM+G5mgv9mFaP+U+l0LjSu+qDSifhixCaypDnQ1FSsk+ogxaekjx5LtyVLDUr1c57YjZWS1G2eSH+41x99G6kUsuzqh7r/nDBTLlXpPNgunVJK/WVIZni3QMm815tZV1KOFq7Yq/n7ZjR/Lp3S5Yf7ZTL8pGIy7fUmYV26KOLJ+lSzphDd2ab4M9J5DwUNjST9JGdy4/YapZyhG4mW3xVf9CN/Lp2V2BXuK7GkVm3TuU4XY6u9yToU3XKSapEeDinSdv1E0nfSV+X20jW2VkP1alomHZoJ89bCW8RWcw+k63JHz/bqbKRzxF+NU1slD/GmTxUfwtp6krsY1SdTi3Quuutcyhqe7+ez8bDgatQcrH1jmAjXdtNgqGvyyMp7JF0H7nrmFxvTketzcuuEt8BSOHn3gWogrCe2A3Me7RedSH1GeuWdy9IVb24beWNkH+PXLeW+IVdeunQ9+Ew6ZyRLJ1byE4xF5s37z5KzmrXOR5eyYfGS9G3ptu2v5nuZHMdljWGm5/BMuqiVOpwuuXGVu9am93VDZrQL68iegyfb4o/bpQ8O0R1xxwvjPN87mxHVG/lEunPN8zyWHWVdUn842deS0e2+e6C45tHcqzCg3Xre3JZrGuVXq/FEIbDt1k65YRpFqftVkMtnv9E6WRzTdG/Sffvh9iOhLXhqN/sh0K5ykUqh3/BF8IfC54YpUJIy9/0KYpd6OQsf/7Y/34guF9TSvNZ95l8HPwb5eWH5i8KdCO0X3vj3pLiSxM+yIGy3AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPzP+Qdk1z4mLA23/gAAAABJRU5ErkJggg==',
                            'IsKlikbaar': True,
                        },
                        'MatchPercentageDAK': 0,
                        'WoonwensMatchOnderdeel': {
                            'List': [],
                            'EmptyListItem': {
                                'Id': '0',
                                'WoonwensOnderdeelId': 0,
                                'WoonwensOnderdeelLabel': '',
                                'IsMatch': False,
                                'WoonwensMatchId': '0',
                                'LaatstGewijzigdOp': '1900-01-01T00:00:00',
                            },
                        },
                        'Lengtegraad': '',
                        'Breedtegraad': '',
                        'IsBewaard': False,
                        'IsVerborgen': False,
                    },
                    '_publicatieInDataFetchStatus': 1,
                    'IsCluster': False,
                    '_isClusterInDataFetchStatus': 1,
                    'PublicatieKandidaatSorteerTekst': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'VolgordeNummer': 0,
                            'OmschrijvingWoonPortaal': '',
                            'Waarde': False,
                            'NatuurlijkPersoonId': '0',
                            'PublicatieId': '0',
                        },
                    },
                    '_publicatieKandidaatSorteerTekstInDataFetchStatus': 0,
                    'GepersonaliseerdeHuur': '0',
                    '_gepersonaliseerdeHuurInDataFetchStatus': 0,
                    'WoonWensList': {
                        'List': [],
                        'EmptyListItem': {
                            'Label': '',
                            'IsMatch': False,
                        },
                    },
                    '_woonWensListInDataFetchStatus': 0,
                    'IsInschrijving': False,
                    '_isInschrijvingInDataFetchStatus': 1,
                    'MatchPercentage': 0,
                    '_matchPercentageInDataFetchStatus': 0,
                    'IsPassend': True,
                    '_isPassendInDataFetchStatus': 0,
                    'ReactieType': '',
                    '_reactieTypeInDataFetchStatus': 0,
                    'IsPreview': False,
                    '_isPreviewInDataFetchStatus': 1,
                    'PreviewPrijsComponenten': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'PublicatieId': '0',
                            'Code': '',
                            'PrijscomponentSoort': '',
                            'PrijscomponentDetailsoort': '',
                            'Bedrag': '0',
                            'BedragBekend': False,
                            'BTW': '',
                            'Begindatum': '1900-01-01',
                            'Einddatum': '1900-01-01',
                        },
                    },
                    '_previewPrijsComponentenInDataFetchStatus': 1,
                    'PreviewSorteerCriteriaList': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'PublicatieId': '0',
                            'Omschrijving': '',
                            'Label': '',
                        },
                    },
                    '_previewSorteerCriteriaListInDataFetchStatus': 1,
                    'PreviewSelectieCriteriaList': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'PublicatieId': '0',
                            'Label': '',
                            'Omschrijving': '',
                        },
                    },
                    '_previewSelectieCriteriaListInDataFetchStatus': 1,
                    'PreviewVertrekkenList': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'PublicatieId': '0',
                            'Oppervlakte': '0',
                            'Inhoud': '0',
                            'Naam': '',
                            'RuimteSoort': '',
                        },
                    },
                    '_previewVertrekkenListInDataFetchStatus': 1,
                    'PreviewPublicatieVoorwaarden': {
                        'Id': '0',
                        'Voorwaarden': None,
                    },
                    '_previewPublicatieVoorwaardenInDataFetchStatus': 1,
                    'PreviewVoorzieningList': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'PublicatieId': '0',
                            'Soort': '',
                            'DetailSoort': '',
                            'Waarde': '',
                        },
                    },
                    '_previewVoorzieningListInDataFetchStatus': 1,
                    'PreviewPublicatieTekst': {
                        'Id': '0',
                        'Tekst': None,
                    },
                    '_previewPublicatieTekstInDataFetchStatus': 1,
                    'PreviewBestandenGeenFotoList': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'PublicatieId': '0',
                            'Titel': '',
                            'Beschrijving': '',
                            'Bestandsnaam': '',
                            'Formaat': '',
                            'Code': '',
                            'Soort': '',
                            'DetailSoort': '',
                            'Primair': False,
                            'Volgordenummer': 0,
                            'Bestandsgrootte': 0,
                            'Bestandslocatie': '',
                        },
                    },
                    '_previewBestandenGeenFotoListInDataFetchStatus': 1,
                    'PreviewVRPlattegrond': {
                        'List': [],
                        'EmptyListItem': {
                            'Id': '0',
                            'PublicatieId': '0',
                            'Titel': '',
                            'Beschrijving': '',
                            'Bestandsnaam': '',
                            'Formaat': '',
                            'Code': '',
                            'Soort': '',
                            'DetailSoort': '',
                            'Primair': False,
                            'Volgordenummer': 0,
                            'Bestandsgrootte': 0,
                            'Bestandslocatie': '',
                        },
                    },
                    '_previewVRPlattegrondInDataFetchStatus': 1,
                    'NatuurlijkPersoonId': '0',
                    '_natuurlijkPersoonIdInDataFetchStatus': 1,
                },
            },
            'clientVariables': {
                'Voorkeuren_LaatsteLogin': '1900-01-01T00:00:00',
                'EnableDarkMode': False,
                'HoofdAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'MK_Tijd': '0',
                'BerichtVerwijderenActief': False,
                'ClientLogEnabled': False,
                'IsVerbergenVraagNietMeer': False,
                'MoetInschrijfKostenBetalen': False,
                'SamenwerkingsverbandId': '2',
                'IsIngelogdMetNumeriekeGebruikersnaam': False,
                'ProfielPanelenIncompleet': '',
                'MFA_ClientSettings': '',
                'OpleidingWRBOmschrijving': '',
                'Weergave_Filters': '[]',
                'MK_Timeout': 10,
                'IsUitgebreidZoeken': False,
                'CacheVariant': 1,
                'ZoekAanbod': '',
                'RegelingWRBNaam': '',
                'QiiInProfiel': False,
                'MFA_Request': '',
                'LastURL': '',
                'IsVerbergKaart': False,
                'InschrijvenVoortzettenMogelijk': False,
                'RegelingIsCompleet': False,
                'MedeAanvragerIngelogd_NatuurlijkPersoonId': '0',
                'IsWeergavePuntenteller': False,
                'MK_Gebruiker': '',
                'SamenwerkingsverbandNaam': 'Regio Amsterdam',
                'Weergave_HeeftFilters': False,
                'SamenwerkingsverbandCode': 'SRA',
                'MFA_Sessie': '',
                'IsMK': False,
                'OpleidingWRBNaam': '',
                'Weergave_SorteringIsAflopend': True,
                'OpleidingIsCompleet': False,
                'Weergave_GebruikWoonwensFilter': True,
                'MK_Token': '',
                'MaandenHistorie': -36,
                'QiiKeuzeRelatiegroepStatusCodeId': 0,
                'MK_Woningzoekende': '',
                'IsWeergaveEinddatum': True,
                'CheckProfielPanelenVoorPopup': True,
                'ToonNieuweProfielBerichten': False,
                'Weergave_HeeftSidebar': False,
                'Weergave_Sortering': 6,
                'RegelingWRBOmschrijving': '',
                'Username': '',
                'MK_Email': '',
                'MFA_RequestId': '0',
                'Weergave_HeeftKaart': True,
            },
        }

        if (oftype == 'publication'):
            return publication_headers, publication_payload
        elif oftype == 'detail':
            return detail_headers, detail_payload
        elif oftype == "name":
            return name_headers, name_payload
        elif oftype == "start":
            return start_headers, start_payload
        else:
            print("invalid form provided")
            return None, None
